web_devp/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, re_path
from requests import delete
from myapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello2/<str:username>/', views.hello2),
    path('index/', views.index),
    path('',views.login),
    path('logout/',views.logout),
    path('hello3/<str:username>', views.hello3),
    path('hello4/<str:username>', views.hello4),
    path('listone/',views.listone),
    path('listall', views.listall),
    path('post1/', views.post1),
    path('post2/', views.post2),
    path('post/',views.post),
    path('index2/', views.index2),
    path('delete/', views.delete),
    path('indextest/',views.indextest),
    path('reply/',views.reply,name='my-view'),
    path('testurl/',views.reply_submit),
    path('will/',views.will),
    path('sign/',views.sign),
    path('inquire/',views.inquire),
    path('edit/<int:id>/', views.edit),
    path('replyshow/<str:id>/<str:mode>',views.replyshow),
    path('replyshow/<str:id>/<str:mode>/<str:select>',views.replyshow),
    #path('replyshow/<str:id>/<str:mode>',views.willselect),
    path('replyupdate/<str:id>/<str:mode>',views.replyUpdate),
    path('edit/<int:id>/<str:mode>', views.edit),
    path('edit2/<int:id>/<str:mode>', views.edit2),
    #path('postform/', postform),
    #path('postreq/', postrequisitionform),
    path('index3/',views.index3),
    path('vote/', views.vote),
    path('login/', views.login),
    path('logout/', views.logout),
    #CLE系統
    path('clereply/', views.clereply),
    path('clesign/', views.clesign),
    path('news/<str:pageindex>/', views.news),
    path('news/', views.news),
    path('detail/<int:detailid>/', views.detail),
    path('replydelete/<str:number>/', views.replydelete),
    path('address/<str:address_id>', views.AddressAPI.as_view(), name='address'),




]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models
from myapp.formatChecker import ContentTypeRestrictedFileField
from django.core.exceptions import ValidationError

# Create your models here.
class student(models.Model):
    cName = models.CharField(max_length=20, null=False)
    cSex = models.CharField(max_length=2, default='M', null=False)
    cBirthday = models.DateTimeField(null=False)
    cEmail = models.EmailField(max_length=100, blank=True, default='')
    cPhone = models.CharField(max_length=50, blank=True, default='')
    cAddr = models.CharField(max_length=255, blank=True, default='')

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return '{0}/{1}'.format(instance.cNumber, filename)


class requisition(models.Model):
    cName = models.CharField(max_length=20, default="")
    cNumber = models.CharField(max_length=20, default="")
    cCusetername = models.CharField(max_length=20, null=False)
    cProjectname = models.CharField(max_length=20, null=False)
    cProjectcode = models.CharField(max_length=20, null=False)
    cLocation = models.CharField(max_length=100, default='')
    cContent = models.CharField(max_length=100, default='')
    cLastproject = models.CharField(max_length=100, default='',blank=True)
    cType = models.CharField(max_length=100, default='')
    cCotpye = models.CharField(max_length=100, default='')
    cProjecttype = models.CharField(max_length=100, default='',blank=True)
    cStage = models.CharField(max_length=100, default='')
    cNoted = models.CharField(max_length=100,default='',blank=True)
    cSchedule = models.CharField(max_length=100,default='',blank=True)
    cSpecial = models.CharField(max_length=100,default='',blank=True)
    cdatestart = models.DateField(null=True, blank=True)
    cdateend = models.DateField(null=True, blank=True)
    cFunction = models.CharField(max_length=20, default='')
    title = models.CharField(max_length = 200, default='',blank=True)
    uploadedFile = models.FileField(upload_to=user_directory_path,default='',blank=True)
    dateTimeOfUpload = models.DateTimeField(auto_now = True)
    cStatus = models.CharField(max_length=20, default="In Progress")
    #cVotename = models.ForeignKey(Vote, on_delete=models.CASCADE, default='')
    def __str__(self):
        return self.cNumber
class Vote(models.Model):  #新聞資料表
    cName =  models.CharField(max_length=10)  #誰投票
    #cVotenumber =  models.CharField(max_length=30, null=False)  #誰投票
    cVotenumber = models.ForeignKey(requisition, on_delete=models.CASCADE,default='')
    cVoteselect = models.BooleanField(default=False)
    cVotetime =  models.DateTimeField(auto_now = True) #投票時間
    def __str__(self):
        return self.cName


class clereply_db(models.Model):
    product = models.CharField(max_length=50, default="")
    checklist = models.CharField(max_length=50, default="")
    producttype = models.CharField(max_length=50, default="")
    productscoreline = models.CharField(max_length=50, default="")

class NewsUnit(models.Model):  #新聞資料表
	catego =  models.CharField(max_length=10, null=False)  #類別關聯
	nickname = models.CharField(max_length=20, null=False)  #暱稱
	title = models.CharField(max_length=50, null=False)  #標題
	message = models.TextField(null=False)  #內容
	pubtime = models.DateTimeField(auto_now=True)  #發布時間
	enabled = models.BooleanField(default=False)  #是否顯示
	press = models.IntegerField(default=0)  #點擊次數
	def __str__(self):
		return self.title

class Type(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
	    return self.name

class Type2(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
	    return self.name

class AddressInfo(models.Model):
    address = models.CharField(max_length = 30, null = True, blank = True, verbose_name = "Function")
    publications = models.ManyToManyField(Type,default='',blank=True)
    publications2 = models.ManyToManyField(Type2,default='',blank=True)
    def __str__(self):
        return self.address



class Worktype(models.Model):
    worktypenumber = models.IntegerField()
    worktypename = models.CharField(max_length = 10)
    def __str__(self):
        return self.worktypename


class Category(models.Model):
    worktypename = models.ForeignKey('Worktype', on_delete=models.CASCADE,default='') #這裏不設置主鍵了
    catid = models.IntegerField() #這裏不設置主鍵了
    categoryname = models.CharField(max_length=50)
    class Meta:
        db_table = 'my_category'
        unique_together = ("catid", "worktypename") #這是重點
    def __int__(self):
        return self.categoryname

class Category2(models.Model):
    worktypename = models.ForeignKey('Worktype', on_delete=models.CASCADE,default='') #這裏不設置主鍵了
    catid = models.IntegerField() #這裏不設置主鍵了
    categoryname = models.CharField(max_length=50)
    class Meta:
        db_table = 'my_category2'
        unique_together = ("catid", "worktypename") #這是重點

class Category3(models.Model):
    worktypename = models.ForeignKey('Worktype', on_delete=models.CASCADE,default='') #這裏不設置主鍵了
    catid = models.IntegerField() #這裏不設置主鍵了
    categoryname = models.CharField(max_length=50)
    class Meta:
        db_table = 'my_category3'
        unique_together = ("catid", "worktypename") #這是重點

templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    {% load static %} <link href="{% static "css/style.css" %}" rel="stylesheet"
    type="text/css" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a href="/index" google-data-stat="頭部導航_logo_1">
        <img src="{% static "images/pegalogo.png" %}" width="140" height="25"
        style="margin-top: -5px;">
      </a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              CLE系統
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/clereply">申請</a>
              <a class="dropdown-item" href="/clesign">簽核</a>
              <a class="dropdown-item" href="/cleinquire">查詢</a>
              <a class="dropdown-item" href="/clereport">報表</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              PM工作需求單
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/reply">申請</a>
              <a class="dropdown-item" href="/will">意願</a>
              <a class="dropdown-item" href="/sign">指派</a>
              <a class="dropdown-item" href="/inquire">查詢</a>
            </div>
          </li>
          {% comment %} 要在這邊寫label {% endcomment %}
        </ul>
        <p  align="right" style="margin-top: 15px;">
          使用者 : {{name}}&ensp;&ensp;<a href="/login/">登出</a>
        </p>
      </div>
    </nav>
  </head>
  <body>

    {% block content %} {% endblock %}
  </body>
  <script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"
  ></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link
    rel="stylesheet"
    href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css"
  />
</html>

templates/clesign.html
<!-- base.html -->
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		{% load static %}
		<link href="{% static "css/style.css" %}" rel="stylesheet"
		type="text/css" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a href="/index" google-data-stat="頭部導航_logo_1">
				<img src="{% static "images/pegalogo.png" %}" width="140" height="38" style="margin-top: -2px;">
			</a>      
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
			  <ul class="navbar-nav mr-auto">
	
				<li class="nav-item dropdown">
				  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					CLE系統
				  </a>
				  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="/clereply">申請</a>
					<a class="dropdown-item" href="/clesign">簽核</a>
					<a class="dropdown-item" href="/cleinquire">查詢</a>
					<a class="dropdown-item" href="/clereport">報表</a>
				  </div>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					  PM工作需求單
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					  <a class="dropdown-item" href="/reply">申請</a>
					  <a class="dropdown-item" href="/will">意願</a>
					  <a class="dropdown-item" href="/sign">簽核</a>
					  <a class="dropdown-item" href="/inquire">查詢</a>
					</div>
				  </li>
				
				{% comment %} 要在這邊寫label {% endcomment %}
			  </ul>
			  <p align=right >使用者 : {{name}}&ensp;&ensp;<a href="/login/">登出</a></p>
			</div>
		  </nav>
	</head>
	<body>
		{% block content %} {% endblock %}
	</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
</html>		

templates/delete.html
{% extends "base.html" %}
{% load static %}
{% block title %}<title>資料表刪除</title>{% endblock %}
{% block content %}
	<h1">student 資料表刪除</h1>
	<form action="." method="POST" name="form1">
		{% csrf_token %}
		<div>請輸入編號：<input type="text" name="cId" />
		</div>
		<div>
		<input type="submit" name="button" id="button" value="確定刪除" />
		</div> 
		<span style="color:red">{{message}}</span>
	</form>
{% endblock %}

templates/edit2.html
{% extends "base.html" %}
{% block title %}<title>資料表修改(二)</title>{% endblock %}
{% block content %}
  <h2>student 資料表修改(二)</h2>
  <form action="/edit2/{{unit.id}}/save" method="POST" name="form1">
	{% csrf_token %}
	<table border="1" cellspacing="1" cellpadding="4">
	  <tr>
		<th>姓名</th>
		<td ><input type="text" id="cName" name="cName" value={{unit.cName}}></td>
	  </tr>
		<th>性別{{unit.cSex}}</th>
		{% if unit.cSex == "M" %}
			<td >
			  <input name="cSex" type="radio" id="cSex1" value="M" checked="checked" />
			  男生
			  <input name="cSex" type="radio" id="cSex2" value="F" />
			  女生
			</td>
		{% else %}
			<td>
			  <input name="cSex" type="radio" id="cSex1" value="M"  />
			  男生
			  <input name="cSex" type="radio" id="cSex2" value="F" checked="checked"/>
			  女生
			</td>
		{% endif %}
	  </tr>
	  <tr>
		<th>生日</th>
		<td><input type="text" id="cBirthday" name="cBirthday" value={{unit.cBirthday}}></td>
	  </tr>
	  <tr>			  
	  <tr>
		<th>郵件帳號</th>
		<td><input type="text" id="cEmail" name="cEmail" value={{unit.cEmail}}></td>
	  </tr>
	  <tr>
		<th >電話</th>
		<td><input type="text" id="cPhone" name="cPhone" value={{unit.cPhone}}></td>
	  </tr>
	  <tr>
		<th>地址</th>
		<td><input type="text" id="cAddr" name="cAddr" value={{unit.cAddr}}></td>
	  </tr>
	  <tr>
		<th colspan="2" align="center">
		  <input type="submit" name="button" id="button" value="送出">
		  <input type="reset" name="button2" id="button2" value="重設"></th>
	  </tr>
	</table>
	<span style="color:red">{{message}}</span>
  </form>
{% endblock %}

templates/hello3.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset ='utf-8'>
        <title>第一個模板</title>
    </head>
<body>
    <h1> 歡迎光臨 : {{username}} </h1>
    <h2> 現在時刻 : {{now}} </h2>
    <input id="startDate" class="Wdate" type="text" onFocus="var endDate=$dp.$('endDate');WdatePicker({onpicked:function(){endDate.focus();},maxDate:'#F{$dp.$D(\'endDate\')}'})"/>
</body>
</html>

templates/hello4.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset ='utf-8'>
        <title>顯示圖片的模板</title>
        {% load static %}
        <link href="{% static "css/style.css" %}" rel="stylesheet"
            type="text/css" />
    </head>
<body>
    <div id="home">
        <img src="{% static "images/ball.png" %}" alt="歡迎光臨"
            width="32" heigh="32" />
        <span class ="info" > 歡迎光臨 : {{username}}</span>
        {% comment %} <span id ="sp1" > 歡迎光臨 : {{username}}</span> {% endcomment %}
        <h2> 現在時刻 : {{now}} </h2> 
    </div>

</body>
</html>
<script
src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
crossorigin="anonymous"
></script>
<script
src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
crossorigin="anonymous"
></script>
<script
src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
crossorigin="anonymous"
></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
$(document).ready(function(){
    $('h2').slideUp(5500);




});
</script>

templates/index.html
{% extends 'base.html' %}
{% block title %}首頁{% endblock %}
{% block content %}
    <h2>系統首頁</h2>
    {% if request.user.is_authenticated %}
    	歡迎光臨</br>
    {% else %}
        <p>您尚未登入喔~</p>
        <a href="/login/">登入</a>
    {% endif %}
    <span style="color:red">{{message}}</span>

{% endblock %}

templates/listone.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset ='utf-8'>
        <title>顯示一筆資料</title>
    </head>
    <body>
        <h2> 現在時刻 : {{now}} </h2>
        <h2>顯示 student資料表一筆資料 {{errormessage}}</h2>
        編號 : {{unit.id}} <br />
        姓名 : {{unit.cName}} <br />
        性別 : {{unit.cSex}} <br />
        生日 : {{unit.cBirthday}} <br />
        郵件帳號 : {{unit.cEmail}} <br />
        電話 : {{unit.cPhone}} <br />
        地址 : {{unit.cAddr}} <br />
    </body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bootstrap Simple Login Form</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<style type="text/css">
	.login-form {
		width: 340px;
    	margin: 50px auto;
	}
    .login-form form {
    	margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {
        font-size: 15px;
        font-weight: bold;
    }
</style>
</head>
<body>
<div class="login-form">
    <form action="" method="POST">
        {% csrf_token %}
        <h2 class="text-center">PMRDC系統</h2>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="PEGA帳號" required="required" name="username">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="密碼" required="required" name="password">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
        </div>
        <span style="color:red">{{message}}</span>
    </form>
</div>
</body>

<script>
</script>
</html>

templates/news.html
{% extends "basenews.html" %}
{% load static %} 
{% block content %}
資料有幾筆 : {{datasize}}
	<div class="contentbox">
		<table width="100%" border="1" cellpadding="1" cellspacing="1">
		<tr>
		  <th align="left">分類</th>
		  <th align="left">標題</th>
		  <th align="left">時間</th>
		  <th align="left">點閱</th>
		</tr>
		{% for unit in newsunits %}
			<tr class="alt">
				<td><div class="typeblock">{{ unit.catego }}</div></td>
				<td><a href="/detail/{{unit.id}}/">{{ unit.title }}</a></td>
				<td>{{ unit.pubtime }}</td>
				<td>{{ unit.press }}</td>
			</tr>
		{% empty %}
			<div class="status warning">
				<p><img src="{% static "images/icon_warning.png" %}" alt="Warning" /><span>注意</span> 目前新聞資料庫中沒有任何資料！</p>
			</div>
		{% endfor %}
		</table>
		<div class="topfunction">
			{% if currentpage > 1 %}
				<a href="/index/1/" title="上一頁">
				<img src="{% static "images/prevpage.png" %}" alt="上一頁" width="64" height="24" /></a>
			{% endif %}
			{% if currentpage < totpage %}
				<a href="/index/2/" title="下一頁">
				<img src="{% static "images/nextpage.png" %}" alt="下一頁" width="64" height="24" /></a>
			{% endif %}
		</div>
	</div>
{% endblock %}

templates/post2.html
{% extends "base.html" %}
{% block title %}<title>資料表新增(二)</title>{% endblock %}
{% block content %}
  <h2>student 資料表新增(二)</h2>
  <form action="." method="POST" name="form1">
	{% csrf_token %}
	<table border="1" cellspacing="1" cellpadding="4">
	  <tr><th >姓名</th><td >{{postform.cName}}</td></tr>
	  <tr>
		<th>性別</th>
		<td >
		  <input name="cSex" type="radio" id="cSex1" value="M" checked="checked" />男生
		  <input name="cSex" type="radio" id="cSex2" value="F" />女生
		</td>
	  </tr>
	  <tr><th>生日</th><td>{{postform.cBirthday}}</td></tr>
	  <tr><th>郵件帳號</th><td>{{postform.cEmail}}</td></tr>
	  <tr><th>電話</th><td >{{postform.cPhone}}</td></tr>
	  <tr><th>地址</th><td >{{postform.cAddr}}</td></tr>
	  <tr>
		<th align="center" >
		  <input type="submit" name="button" id="button" value="送出">
		  <input type="reset" name="button2" id="button2" value="重設"></th>
	  </tr>
	</table>
</form>
	<span style="color:red">{{message}}</span>
	
{% endblock %}

templates/will.html
{% extends 'base.html' %}
{% block title %}申請表單查詢{% endblock %}
{% block content %}
{% load static %}
{{message}}{{number}}

<div class = 'info'><br>
</div>
<div class = 'info'><br>
</div>
<div class ="row">
    <div class="col-3">

    </div>
    <div class="col-6">
        <div >
            <table class="table table-bordered" width="100%">
            <tr>
              <th align="left">單號</th>
              <th align="left">Fuction</th>
              <th align="left">開發類型</th>
              <th align="left">客戶名稱</th>
              <th align="left">專案名稱</th>
              <th align="left">工作內容</th>
              <th align="left">狀態</th>
              <th align="left">投票選擇</th>
            </tr>
            {% for unit in worklist %}

                <tr class="alt">
                <td><a href="../replyshow/{{unit.cNumber}}/will">{{ unit.cNumber }}</a></td>
                <td>{{ unit.cFunction }}</td>
                <td>{{ unit.cType }}</td>
                <td>{{ unit.cCusetername }}</td>
                <td>{{ unit.cProjectname }}</td>
                <td>{{ unit.cContent }}</td>
                {% if unit.cStatus == "In Progress" %}
                <td><font color="white" style="background-color:MediumSeaGreen;">{{ unit.cStatus }}</font></td>
                {% else %}
                <td>{{ unit.cStatus }}</td>
                {% endif %}

                {% for i in unit.vote_set.all %}
                    {% if i.cVoteselect == True %}
                        <td>有意願&nbsp;&nbsp;<img src="{% static "images/voteyes.png" %}" ></td>
                    {% elif i.cVoteselect == False %}
                        <td>無意願&nbsp;&nbsp;<img src="{% static "images/voteno.png" %}" ></td>
                    {% endif %}
                    {% empty %}<td>尚未投票</td>
                {% endfor %}
                </tr>
            {% empty %}
                <div class="status warning">
                    <p align="center"><img src="{% static "images/icon_warning.png" %}" alt="Warning" />目前無任何申請單 </p>
                </div>
            {% endfor %}
            </table>
    </div>
    <div class="col-3">
        
    </div>

</div>

{% csrf_token %}
<script type="text/javascript">
    function change(){
        window.alert("彈跳視窗想要顯示的文字");

    }
	} 
</script>


{% endblock %}